# These are supported funding model platforms

github: [avosa, Rabin-Nyaundi] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., 
tidelift: npm/babel, django # Replace with a single Tidelift platform-name/package-name e.g., npm/babel

